# Generated by Django 4.2.15 on 2024-08-11 10:17

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='exercise',
            name='detailed_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='detailed_image'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
