# Generated by Django 4.2.15 on 2024-08-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_reportcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportComment',
        ),
    ]
