# Generated by Django 4.2.15 on 2024-08-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_created_at_exercise_detailed_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
