# Generated by Django 4.2.15 on 2024-08-27 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_alter_exercise_description_alter_exercise_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreport',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='commentreport',
            name='created_at',
        ),
        migrations.AddField(
            model_name='commentreport',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercises.comment'),
            preserve_default=False,
        ),
    ]
