# Generated by Django 4.2.15 on 2024-08-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_remove_commentreport_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-08-26 00:00:00'),
            preserve_default=False,
        ),
    ]
