# Generated by Django 4.2.15 on 2024-08-21 16:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_exercise_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='additional_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='additional_image'),
        ),
    ]
